### ISSUE TITLE
Registry for CI tests seem out of date (missing #37251)?

### ISSUE THREAD

**Issue by dehann** [JuliaRegistries/General#37344] opened 2021-05-23 22:48 UTC
Hi,

This issue probably sounds highly unusual, but I have tried almost everything on effected Travis and GitHub Actions but the following problem persists.  All works fine on my local machine, but the cloud instances are getting different registry results...  

During CI tests of downstream packages trying to upgrade to Manifolds v0.5.0, it looks like the content of PR  #37251 is not being picked up by the CI instances (both Travis and GitHub Actions).

Based on many CI trails I have been working through today, here is a representative minimum example -- [taken from Travis](https://travis-ci.org/github/JuliaRobotics/ApproxManifoldProducts.jl/jobs/772113734)  and here is a similar one on [Actions](https://github.com/JuliaRobotics/IncrementalInference.jl/runs/2650588228?check_suite_focus=true):

```julia
$ julia --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.clone(pwd()); Pkg.build(\"${JL_PKG}\"); else using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end; end"

Installing known registries into `~/.julia`
Added registry `General` to `~/.julia/registries/General`
Updating registry at `~/.julia/registries/General`

ERROR: Unsatisfiable requirements detected for package Manifolds [1cead3c2]:
 Manifolds [1cead3c2] log:
 ├─possible versions are: 0.1.0-0.4.27 or uninstalled
 └─restricted to versions 0.5 by ApproxManifoldProducts [9bbbb610] — no versions left
   └─ApproxManifoldProducts [9bbbb610] log:
     ├─possible versions are: 0.3.4 or uninstalled
     └─ApproxManifoldProducts [9bbbb610] is fixed to version 0.3.4
```

Notice Manifolds only go up to v0.4.  Yet, I'm able to work with Manifolds v0.5.0 just fine on my local computer:
```julia
(dfg) pkg> st
      Status `/tmp/dfg/Project.toml`
  [9bbbb610] ApproxManifoldProducts v0.3.4 `https://github.com/JuliaRobotics/ApproxManifoldProducts.jl.git#master`
  [1cead3c2] Manifolds v0.5.0
```

I'm pretty sure I'm doing everything right, but clearly something is amiss.  Is it possible that the cloud instances have a bad cache in the background, or something invisible preventing CI from installing `Manifolds v0.5.0`?  If the CI tests are setup wrong somehow, I'm definitely not seeing it and have been carefully looking at this for quite some time.

Look, here is the Manifolds v0.5.0 entry in the registry as expected???
https://github.com/JuliaRegistries/General/blob/af0ebef67dd4aaf9c4ba8de8efa1ff64974f8396/M/Manifolds/Versions.toml#L163-L164

----

For posterity, here are the environment toml files from my local machine where Manifolds@v0.5.0 installs and works as expected.

[dfg_env.zip](https://github.com/JuliaRegistries/General/files/6529019/dfg_env.zip)

Any advise would be greatly appreciated, thanks in advance!

**Comment by DilumAluthge** [comment] 2021-05-23 22:56
Duplicate of 16777

**Comment by DilumAluthge** [comment] 2021-05-23 22:56
Duplicate of #16777

**Closed by DilumAluthge** 2021-05-23 22:56 UTC
