### ISSUE TITLE
Broken repo links

### ISSUE THREAD

**Issue by Gregliest** [JuliaRegistries/General#40108] opened 2021-07-02 17:24 UTC
I was exploring the registry today, and I found 28 packages whose repositories (listed in Project.toml) don't seem to exist anymore. After a conversation on Slack, it sounds like this shouldn't break anything, since the package servers should have a copy of each version. However, I tried installing a couple of the packages and was unable to get them to work. 

In either case, it seems to me that the registry might not want to include broken links. However, I'm not sure of the best path forward, or even if an action here is worthwhile. Some potential ideas could be to simply delete the stale repo links from the Project.toml file, or to have some automated process that checks links and notifies package owners that their link is broken. 

If an action is warranted here, I'm happy to take on the project. 

Here's the list of broken links:

https://github.com/MUsmanZahid/TeXTable.jl
https://github.com/PetrKryslUCSD/MeshPorter.jl
https://github.com/mipals/SymSemiseparableMatrices.jl
https://github.com/owinter92/SimpleTweaks.jl
https://github.com/rjdverbeek-tud/Atmosphere.jl
https://github.com/anders-dc/Granular.jl
https://github.com/StanJulia/StanMCMCChain.jl
https://github.com/slmcbane/MirroredArrayViews.jl
https://github.com/mrtkp9993/Bioinformatics.jl
https://github.com/JonathanCourtois/MackeyGlass.jl
https://github.com/GuilhermeHaetinger/KelvinletsImage.jl
https://github.com/bcbi/CountdownNumbers.jl
https://github.com/MasFlam/Tui4jl
https://github.com/PetrKryslUCSD/MeshKeeper.jl
https://github.com/markushhh/YahooFinance.jl
https://github.com/louiscmm/Sinaica.jl
https://github.com/PetrKryslUCSD/MeshMaker.jl
https://github.com/bcbi/CountdownLetters.jl
https://github.com/tlienart/MLJScikitLearn.jl
https://github.com/Geographs/AuthGG.jl
https://github.com/MUsmanZahid/DTALib.jl
https://github.com/extradosages/RestApis.jl
https://github.com/PetrKryslUCSD/MeshFinder.jl
https://github.com/Moelf/BigG.jl
https://github.com/atoptima/HighLevelTypes.jl
https://github.com/rbalexan/InfrastructureSensing.jl
https://github.com/lucianolorenti/Estapir.jl
https://github.com/oscar-system/GAPTypes.jl

**Comment by DilumAluthge** [comment] 2021-07-02 17:32
Duplicate of 19033?

**Comment by DilumAluthge** [comment] 2021-07-02 17:45
Duplicate of #19033

**Closed by DilumAluthge** 2021-07-02 17:45 UTC
